version: '3.3'

services:
  server:
    build: .
    ports:
      - "9100:8080"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'enrollee'
      MYSQL_USER: 'wt'
      MYSQL_PASSWORD: '123321'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '11111:3306'
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
